<a href="https://colab.research.google.com/github/aimlhoney/LENDING_CLUB_CASE_STUDY/blob/master/Lending_club_case_study.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

In [17]:
pd.set_option('display.max_rows', 500)

In [18]:
loan_data_set = pd.read_csv('https://cdn.upgrad.com/UpGrad/temp/3ba74fb7-bd88-4854-8597-1c225a5aed99/loan.zip')

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (47) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [19]:
loan_data_set

            id  member_id  ...  total_bc_limit  total_il_high_credit_limit
0      1077501    1296599  ...             NaN                         NaN
1      1077430    1314167  ...             NaN                         NaN
2      1077175    1313524  ...             NaN                         NaN
3      1076863    1277178  ...             NaN                         NaN
4      1075358    1311748  ...             NaN                         NaN
...        ...        ...  ...             ...                         ...
39712    92187      92174  ...             NaN                         NaN
39713    90665      90607  ...             NaN                         NaN
39714    90395      90390  ...             NaN                         NaN
39715    90376      89243  ...             NaN                         NaN
39716    87023      86999  ...             NaN                         NaN

[39717 rows x 111 columns]

In [20]:
data_dictionary = pd.read_excel('https://cdn.upgrad.com/UpGrad/temp/af860da6-f838-47d6-ad97-551022550ee4/Data_Dictionary.xlsx')

In [21]:
data_dictionary

                        LoanStatNew                                        Description
0                    acc_now_delinq  The number of accounts on which the borrower i...
1              acc_open_past_24mths         Number of trades opened in past 24 months.
2                        addr_state  The state provided by the borrower in the loan...
3                          all_util              Balance to credit limit on all trades
4                        annual_inc  The self-reported annual income provided by th...
5                  annual_inc_joint  The combined self-reported annual income provi...
6                  application_type  Indicates whether the loan is an individual ap...
7                       avg_cur_bal            Average current balance of all accounts
8                    bc_open_to_buy          Total open to buy on revolving bankcards.
9                           bc_util  Ratio of total current balance to high credit/...
10         chargeoff_within_12_mths             Number of charge-offs within 12 months
11          collection_recovery_fee                     post charge off collection fee
12       collections_12_mths_ex_med  Number of collections in 12 months excluding m...
13                      delinq_2yrs  The number of 30+ days past-due incidences of ...
14                      delinq_amnt  The past-due amount owed for the accounts on w...
15                             desc          Loan description provided by the borrower
16                              dti  A ratio calculated using the borrower’s total ...
17                        dti_joint  A ratio calculated using the co-borrowers' tot...
18                 earliest_cr_line  The month the borrower's earliest reported cre...
19                       emp_length  Employment length in years. Possible values ar...
20                        emp_title  The job title supplied by the Borrower when ap...
21                  fico_range_high  The upper boundary range the borrower’s FICO a...
22                   fico_range_low  The lower boundary range the borrower’s FICO a...
23                      funded_amnt  The total amount committed to that loan at tha...
24                  funded_amnt_inv  The total amount committed by investors for th...
25                            grade                             LC assigned loan grade
26                   home_ownership  The home ownership status provided by the borr...
27                               id      A unique LC assigned ID for the loan listing.
28                          il_util  Ratio of total current balance to high credit/...
29              initial_list_status  The initial listing status of the loan. Possib...
30                           inq_fi               Number of personal finance inquiries
31                     inq_last_12m       Number of credit inquiries in past 12 months
32                   inq_last_6mths  The number of inquiries in past 6 months (excl...
33                      installment  The monthly payment owed by the borrower if th...
34                         int_rate                          Interest Rate on the loan
35                          issue_d                The month which the loan was funded
36               last_credit_pull_d  The most recent month LC pulled credit for thi...
37             last_fico_range_high  The upper boundary range the borrower’s last F...
38              last_fico_range_low  The lower boundary range the borrower’s last F...
39                  last_pymnt_amnt                 Last total payment amount received
40                     last_pymnt_d                    Last month payment was received
41                        loan_amnt  The listed amount of the loan applied for by t...
42                      loan_status                         Current status of the loan
43                       max_bal_bc  Maximum current balance owed on all revolving ...
44                        member_id   A unique LC assigned Id for the borrower member.
45               mo_sin_old_il_acct  Months since oldest bank installment account o...
46             mo_sin_old_rev_tl_op       Months since oldest revolving account opened
47            mo_sin_rcnt_rev_tl_op  Months since most recent revolving account opened
48                   mo_sin_rcnt_tl            Months since most recent account opened
49                         mort_acc                       Number of mortgage accounts.
50           mths_since_last_delinq  The number of months since the borrower's last...
51      mths_since_last_major_derog    Months since most recent 90-day or worse rating
52           mths_since_last_record  The number of months since the last public rec...
53               mths_since_rcnt_il  Months since most recent installment accounts ...
54             mths_since_recent_bc  Months since most recent bankcard account opened.
55         mths_since_recent_bc_dlq      Months since most recent bankcard delinquency
56            mths_since_recent_inq                  Months since most recent inquiry.
57   mths_since_recent_revol_delinq    Months since most recent revolving delinquency.
58                     next_pymnt_d                        Next scheduled payment date
59            num_accts_ever_120_pd  Number of accounts ever 120 or more days past due
60                   num_actv_bc_tl       Number of currently active bankcard accounts
61                  num_actv_rev_tl        Number of currently active revolving trades
62                      num_bc_sats           Number of satisfactory bankcard accounts
63                        num_bc_tl                        Number of bankcard accounts
64                        num_il_tl                     Number of installment accounts
65                    num_op_rev_tl                  Number of open revolving accounts
66                    num_rev_accts                       Number of revolving accounts
67              num_rev_tl_bal_gt_0         Number of revolving trades with balance >0
68                         num_sats                    Number of satisfactory accounts
69                 num_tl_120dpd_2m  Number of accounts currently 120 days past due...
70                     num_tl_30dpd  Number of accounts currently 30 days past due ...
71               num_tl_90g_dpd_24m  Number of accounts 90 or more days past due in...
72               num_tl_op_past_12m        Number of accounts opened in past 12 months
73                         open_acc  The number of open credit lines in the borrowe...
74                      open_acc_6m             Number of open trades in last 6 months
75                      open_il_12m  Number of installment accounts opened in past ...
76                      open_il_24m  Number of installment accounts opened in past ...
77                       open_il_6m      Number of currently active installment trades
78                      open_rv_12m  Number of revolving trades opened in past 12 m...
79                      open_rv_24m  Number of revolving trades opened in past 24 m...
80                        out_prncp  Remaining outstanding principal for total amou...
81                    out_prncp_inv  Remaining outstanding principal for portion of...
82                   pct_tl_nvr_dlq                 Percent of trades never delinquent
83                 percent_bc_gt_75  Percentage of all bankcard accounts > 75% of l...
84                      policy_code  publicly available policy_code=1\nnew products...
85                          pub_rec                Number of derogatory public records
86             pub_rec_bankruptcies               Number of public record bankruptcies
87                          purpose  A category provided by the borrower for the lo...
88                       pymnt_plan  Indicates if a payment plan has been put in pl...
89                       recoveries                     post charge off gross recovery
90                        revol_bal                     Total credit revolving balance
91                       revol_util  Revolving line utilization rate, or the amount...
92                        sub_grade                          LC assigned loan subgrade
93                        tax_liens                                Number of tax liens
94                             term  The number of payments on the loan. Values are...
95                            title            The loan title provided by the borrower
96                     tot_coll_amt                 Total collection amounts ever owed
97                      tot_cur_bal              Total current balance of all accounts
98                  tot_hi_cred_lim                     Total high credit/credit limit
99                        total_acc  The total number of credit lines currently in ...
100               total_bal_ex_mort            Total credit balance excluding mortgage
101                    total_bal_il  Total current balance of all installment accounts
102                  total_bc_limit            Total bankcard high credit/credit limit
103                     total_cu_tl                           Number of finance trades
104      total_il_high_credit_limit         Total installment high credit/credit limit
105                     total_pymnt  Payments received to date for total amount funded
106                 total_pymnt_inv  Payments received to date for portion of total...
107                   total_rec_int                          Interest received to date
108              total_rec_late_fee                         Late fees received to date
109                 total_rec_prncp                         Principal received to date
110              total_rev_hi_lim             Total revolving high credit/credit limit
111                             url             URL for the LC page with listing data.
112             verification_status  Indicates if income was verified by LC, not ve...
113           verified_status_joint  Indicates if the co-borrowers' joint income wa...
114                        zip_code  The first 3 numbers of the zip code provided b...
115                             NaN                                                NaN
116                             NaN  * Employer Title replaces Employer Name for al...

In [22]:
data_dictionary.columns

Index(['LoanStatNew', 'Description'], dtype='object')

In [23]:
loan_data_set.isnull().sum()

id                                    0
member_id                             0
loan_amnt                             0
funded_amnt                           0
funded_amnt_inv                       0
term                                  0
int_rate                              0
installment                           0
grade                                 0
sub_grade                             0
emp_title                          2459
emp_length                         1075
home_ownership                        0
annual_inc                            0
verification_status                   0
issue_d                               0
loan_status                           0
pymnt_plan                            0
url                                   0
desc                              12940
purpose                               0
title                                11
zip_code                              0
addr_state                            0
dti                                   0
delinq_2yrs                           0
earliest_cr_line                      0
inq_last_6mths                        0
mths_since_last_delinq            25682
mths_since_last_record            36931
open_acc                              0
pub_rec                               0
revol_bal                             0
revol_util                           50
total_acc                             0
initial_list_status                   0
out_prncp                             0
out_prncp_inv                         0
total_pymnt                           0
total_pymnt_inv                       0
total_rec_prncp                       0
total_rec_int                         0
total_rec_late_fee                    0
recoveries                            0
collection_recovery_fee               0
last_pymnt_d                         71
last_pymnt_amnt                       0
next_pymnt_d                      38577
last_credit_pull_d                    2
collections_12_mths_ex_med           56
mths_since_last_major_derog       39717
policy_code                           0
application_type                      0
annual_inc_joint                  39717
dti_joint                         39717
verification_status_joint         39717
acc_now_delinq                        0
tot_coll_amt                      39717
tot_cur_bal                       39717
open_acc_6m                       39717
open_il_6m                        39717
open_il_12m                       39717
open_il_24m                       39717
mths_since_rcnt_il                39717
total_bal_il                      39717
il_util                           39717
open_rv_12m                       39717
open_rv_24m                       39717
max_bal_bc                        39717
all_util                          39717
total_rev_hi_lim                  39717
inq_fi                            39717
total_cu_tl                       39717
inq_last_12m                      39717
acc_open_past_24mths              39717
avg_cur_bal                       39717
bc_open_to_buy                    39717
bc_util                           39717
chargeoff_within_12_mths             56
delinq_amnt                           0
mo_sin_old_il_acct                39717
mo_sin_old_rev_tl_op              39717
mo_sin_rcnt_rev_tl_op             39717
mo_sin_rcnt_tl                    39717
mort_acc                          39717
mths_since_recent_bc              39717
mths_since_recent_bc_dlq          39717
mths_since_recent_inq             39717
mths_since_recent_revol_delinq    39717
num_accts_ever_120_pd             39717
num_actv_bc_tl                    39717
num_actv_rev_tl                   39717
num_bc_sats                       39717
num_bc_tl                         39717
num_il_tl                         39717
num_op_rev_tl                     39717
num_rev_accts                     39717
num_rev_tl_bal_gt_0               39717
num_sats                          39717
num_tl_120dpd_2m                  39717
num_tl_30dpd                      39717
num_tl_90g_dpd_24m                39717
num_tl_op_past_12m                39717
pct_tl_nvr_dlq                    39717
percent_bc_gt_75                  39717
pub_rec_bankruptcies                697
tax_liens                            39
tot_hi_cred_lim                   39717
total_bal_ex_mort                 39717
total_bc_limit                    39717
total_il_high_credit_limit        39717
dtype: int64

In [24]:
loan_data_set.columns

Index(['id', 'member_id', 'loan_amnt', 'funded_amnt', 'funded_amnt_inv',
       'term', 'int_rate', 'installment', 'grade', 'sub_grade',
       ...
       'num_tl_90g_dpd_24m', 'num_tl_op_past_12m', 'pct_tl_nvr_dlq',
       'percent_bc_gt_75', 'pub_rec_bankruptcies', 'tax_liens',
       'tot_hi_cred_lim', 'total_bal_ex_mort', 'total_bc_limit',
       'total_il_high_credit_limit'],
      dtype='object', length=111)

In [25]:
loan_data_set.describe()

                 id     member_id  ...  total_bc_limit  total_il_high_credit_limit
count  3.971700e+04  3.971700e+04  ...             0.0                         0.0
mean   6.831319e+05  8.504636e+05  ...             NaN                         NaN
std    2.106941e+05  2.656783e+05  ...             NaN                         NaN
min    5.473400e+04  7.069900e+04  ...             NaN                         NaN
25%    5.162210e+05  6.667800e+05  ...             NaN                         NaN
50%    6.656650e+05  8.508120e+05  ...             NaN                         NaN
75%    8.377550e+05  1.047339e+06  ...             NaN                         NaN
max    1.077501e+06  1.314167e+06  ...             NaN                         NaN

[8 rows x 87 columns]

In [73]:
round(loan_data_set.isnull().sum()/len(loan_data_set)*100,2)

id                                  0.00
member_id                           0.00
loan_amnt                           0.00
funded_amnt                         0.00
funded_amnt_inv                     0.00
term                                0.00
int_rate                            0.00
installment                         0.00
grade                               0.00
sub_grade                           0.00
emp_title                           6.19
emp_length                          2.71
home_ownership                      0.00
annual_inc                          0.00
verification_status                 0.00
issue_d                             0.00
loan_status                         0.00
pymnt_plan                          0.00
url                                 0.00
desc                               32.58
purpose                             0.00
title                               0.03
zip_code                            0.00
addr_state                          0.00
dti                                 0.00
delinq_2yrs                         0.00
earliest_cr_line                    0.00
inq_last_6mths                      0.00
mths_since_last_delinq             64.66
mths_since_last_record             92.99
open_acc                            0.00
pub_rec                             0.00
revol_bal                           0.00
revol_util                          0.13
total_acc                           0.00
initial_list_status                 0.00
out_prncp                           0.00
out_prncp_inv                       0.00
total_pymnt                         0.00
total_pymnt_inv                     0.00
total_rec_prncp                     0.00
total_rec_int                       0.00
total_rec_late_fee                  0.00
recoveries                          0.00
collection_recovery_fee             0.00
last_pymnt_d                        0.18
last_pymnt_amnt                     0.00
next_pymnt_d                       97.13
last_credit_pull_d                  0.01
collections_12_mths_ex_med          0.14
mths_since_last_major_derog       100.00
policy_code                         0.00
application_type                    0.00
annual_inc_joint                  100.00
dti_joint                         100.00
verification_status_joint         100.00
acc_now_delinq                      0.00
tot_coll_amt                      100.00
tot_cur_bal                       100.00
open_acc_6m                       100.00
open_il_6m                        100.00
open_il_12m                       100.00
open_il_24m                       100.00
mths_since_rcnt_il                100.00
total_bal_il                      100.00
il_util                           100.00
open_rv_12m                       100.00
open_rv_24m                       100.00
max_bal_bc                        100.00
all_util                          100.00
total_rev_hi_lim                  100.00
inq_fi                            100.00
total_cu_tl                       100.00
inq_last_12m                      100.00
acc_open_past_24mths              100.00
avg_cur_bal                       100.00
bc_open_to_buy                    100.00
bc_util                           100.00
chargeoff_within_12_mths            0.14
delinq_amnt                         0.00
mo_sin_old_il_acct                100.00
mo_sin_old_rev_tl_op              100.00
mo_sin_rcnt_rev_tl_op             100.00
mo_sin_rcnt_tl                    100.00
mort_acc                          100.00
mths_since_recent_bc              100.00
mths_since_recent_bc_dlq          100.00
mths_since_recent_inq             100.00
mths_since_recent_revol_delinq    100.00
num_accts_ever_120_pd             100.00
num_actv_bc_tl                    100.00
num_actv_rev_tl                   100.00
num_bc_sats                       100.00
num_bc_tl                         100.00
num_il_tl                         100.00
num_op_rev_tl                     100.00
num_rev_accts                     100.00
num_rev_tl_bal_gt_0               100.00
num_sats                          100.00
num_tl_120dpd_2m                  100.00
num_tl_30dpd                      100.00
num_tl_90g_dpd_24m                100.00
num_tl_op_past_12m                100.00
pct_tl_nvr_dlq                    100.00
percent_bc_gt_75                  100.00
pub_rec_bankruptcies                1.75
tax_liens                           0.10
tot_hi_cred_lim                   100.00
total_bal_ex_mort                 100.00
total_bc_limit                    100.00
total_il_high_credit_limit        100.00
dtype: float64

In [74]:
# There are several columns which has all null values, let's drop these all columns
loan_data_set = loan_data_set.drop(['total_il_high_credit_limit','total_bc_limit','total_bal_ex_mort','tot_hi_cred_lim'], axis =1)

In [75]:
round(loan_data_set.isnull().sum()/len(loan_data_set)*100,2)

id                                  0.00
member_id                           0.00
loan_amnt                           0.00
funded_amnt                         0.00
funded_amnt_inv                     0.00
term                                0.00
int_rate                            0.00
installment                         0.00
grade                               0.00
sub_grade                           0.00
emp_title                           6.19
emp_length                          2.71
home_ownership                      0.00
annual_inc                          0.00
verification_status                 0.00
issue_d                             0.00
loan_status                         0.00
pymnt_plan                          0.00
url                                 0.00
desc                               32.58
purpose                             0.00
title                               0.03
zip_code                            0.00
addr_state                          0.00
dti                                 0.00
delinq_2yrs                         0.00
earliest_cr_line                    0.00
inq_last_6mths                      0.00
mths_since_last_delinq             64.66
mths_since_last_record             92.99
open_acc                            0.00
pub_rec                             0.00
revol_bal                           0.00
revol_util                          0.13
total_acc                           0.00
initial_list_status                 0.00
out_prncp                           0.00
out_prncp_inv                       0.00
total_pymnt                         0.00
total_pymnt_inv                     0.00
total_rec_prncp                     0.00
total_rec_int                       0.00
total_rec_late_fee                  0.00
recoveries                          0.00
collection_recovery_fee             0.00
last_pymnt_d                        0.18
last_pymnt_amnt                     0.00
next_pymnt_d                       97.13
last_credit_pull_d                  0.01
collections_12_mths_ex_med          0.14
mths_since_last_major_derog       100.00
policy_code                         0.00
application_type                    0.00
annual_inc_joint                  100.00
dti_joint                         100.00
verification_status_joint         100.00
acc_now_delinq                      0.00
tot_coll_amt                      100.00
tot_cur_bal                       100.00
open_acc_6m                       100.00
open_il_6m                        100.00
open_il_12m                       100.00
open_il_24m                       100.00
mths_since_rcnt_il                100.00
total_bal_il                      100.00
il_util                           100.00
open_rv_12m                       100.00
open_rv_24m                       100.00
max_bal_bc                        100.00
all_util                          100.00
total_rev_hi_lim                  100.00
inq_fi                            100.00
total_cu_tl                       100.00
inq_last_12m                      100.00
acc_open_past_24mths              100.00
avg_cur_bal                       100.00
bc_open_to_buy                    100.00
bc_util                           100.00
chargeoff_within_12_mths            0.14
delinq_amnt                         0.00
mo_sin_old_il_acct                100.00
mo_sin_old_rev_tl_op              100.00
mo_sin_rcnt_rev_tl_op             100.00
mo_sin_rcnt_tl                    100.00
mort_acc                          100.00
mths_since_recent_bc              100.00
mths_since_recent_bc_dlq          100.00
mths_since_recent_inq             100.00
mths_since_recent_revol_delinq    100.00
num_accts_ever_120_pd             100.00
num_actv_bc_tl                    100.00
num_actv_rev_tl                   100.00
num_bc_sats                       100.00
num_bc_tl                         100.00
num_il_tl                         100.00
num_op_rev_tl                     100.00
num_rev_accts                     100.00
num_rev_tl_bal_gt_0               100.00
num_sats                          100.00
num_tl_120dpd_2m                  100.00
num_tl_30dpd                      100.00
num_tl_90g_dpd_24m                100.00
num_tl_op_past_12m                100.00
pct_tl_nvr_dlq                    100.00
percent_bc_gt_75                  100.00
pub_rec_bankruptcies                1.75
tax_liens                           0.10
dtype: float64

In [76]:
loan_data_set = loan_data_set.drop(['percent_bc_gt_75','pct_tl_nvr_dlq','num_tl_op_past_12m','num_tl_90g_dpd_24m'], axis =1)

In [77]:
round(loan_data_set.isnull().sum()/len(loan_data_set)*100,2)

id                                  0.00
member_id                           0.00
loan_amnt                           0.00
funded_amnt                         0.00
funded_amnt_inv                     0.00
term                                0.00
int_rate                            0.00
installment                         0.00
grade                               0.00
sub_grade                           0.00
emp_title                           6.19
emp_length                          2.71
home_ownership                      0.00
annual_inc                          0.00
verification_status                 0.00
issue_d                             0.00
loan_status                         0.00
pymnt_plan                          0.00
url                                 0.00
desc                               32.58
purpose                             0.00
title                               0.03
zip_code                            0.00
addr_state                          0.00
dti                                 0.00
delinq_2yrs                         0.00
earliest_cr_line                    0.00
inq_last_6mths                      0.00
mths_since_last_delinq             64.66
mths_since_last_record             92.99
open_acc                            0.00
pub_rec                             0.00
revol_bal                           0.00
revol_util                          0.13
total_acc                           0.00
initial_list_status                 0.00
out_prncp                           0.00
out_prncp_inv                       0.00
total_pymnt                         0.00
total_pymnt_inv                     0.00
total_rec_prncp                     0.00
total_rec_int                       0.00
total_rec_late_fee                  0.00
recoveries                          0.00
collection_recovery_fee             0.00
last_pymnt_d                        0.18
last_pymnt_amnt                     0.00
next_pymnt_d                       97.13
last_credit_pull_d                  0.01
collections_12_mths_ex_med          0.14
mths_since_last_major_derog       100.00
policy_code                         0.00
application_type                    0.00
annual_inc_joint                  100.00
dti_joint                         100.00
verification_status_joint         100.00
acc_now_delinq                      0.00
tot_coll_amt                      100.00
tot_cur_bal                       100.00
open_acc_6m                       100.00
open_il_6m                        100.00
open_il_12m                       100.00
open_il_24m                       100.00
mths_since_rcnt_il                100.00
total_bal_il                      100.00
il_util                           100.00
open_rv_12m                       100.00
open_rv_24m                       100.00
max_bal_bc                        100.00
all_util                          100.00
total_rev_hi_lim                  100.00
inq_fi                            100.00
total_cu_tl                       100.00
inq_last_12m                      100.00
acc_open_past_24mths              100.00
avg_cur_bal                       100.00
bc_open_to_buy                    100.00
bc_util                           100.00
chargeoff_within_12_mths            0.14
delinq_amnt                         0.00
mo_sin_old_il_acct                100.00
mo_sin_old_rev_tl_op              100.00
mo_sin_rcnt_rev_tl_op             100.00
mo_sin_rcnt_tl                    100.00
mort_acc                          100.00
mths_since_recent_bc              100.00
mths_since_recent_bc_dlq          100.00
mths_since_recent_inq             100.00
mths_since_recent_revol_delinq    100.00
num_accts_ever_120_pd             100.00
num_actv_bc_tl                    100.00
num_actv_rev_tl                   100.00
num_bc_sats                       100.00
num_bc_tl                         100.00
num_il_tl                         100.00
num_op_rev_tl                     100.00
num_rev_accts                     100.00
num_rev_tl_bal_gt_0               100.00
num_sats                          100.00
num_tl_120dpd_2m                  100.00
num_tl_30dpd                      100.00
pub_rec_bankruptcies                1.75
tax_liens                           0.10
dtype: float64

In [78]:
loan_data_set = loan_data_set.drop(['num_tl_30dpd','num_tl_120dpd_2m','num_sats','num_rev_tl_bal_gt_0','num_rev_accts','num_op_rev_tl','num_il_tl','num_bc_tl','num_bc_sats','num_actv_rev_tl'], axis =1)

In [79]:
round(loan_data_set.isnull().sum()/len(loan_data_set)*100,2)

id                                  0.00
member_id                           0.00
loan_amnt                           0.00
funded_amnt                         0.00
funded_amnt_inv                     0.00
term                                0.00
int_rate                            0.00
installment                         0.00
grade                               0.00
sub_grade                           0.00
emp_title                           6.19
emp_length                          2.71
home_ownership                      0.00
annual_inc                          0.00
verification_status                 0.00
issue_d                             0.00
loan_status                         0.00
pymnt_plan                          0.00
url                                 0.00
desc                               32.58
purpose                             0.00
title                               0.03
zip_code                            0.00
addr_state                          0.00
dti                                 0.00
delinq_2yrs                         0.00
earliest_cr_line                    0.00
inq_last_6mths                      0.00
mths_since_last_delinq             64.66
mths_since_last_record             92.99
open_acc                            0.00
pub_rec                             0.00
revol_bal                           0.00
revol_util                          0.13
total_acc                           0.00
initial_list_status                 0.00
out_prncp                           0.00
out_prncp_inv                       0.00
total_pymnt                         0.00
total_pymnt_inv                     0.00
total_rec_prncp                     0.00
total_rec_int                       0.00
total_rec_late_fee                  0.00
recoveries                          0.00
collection_recovery_fee             0.00
last_pymnt_d                        0.18
last_pymnt_amnt                     0.00
next_pymnt_d                       97.13
last_credit_pull_d                  0.01
collections_12_mths_ex_med          0.14
mths_since_last_major_derog       100.00
policy_code                         0.00
application_type                    0.00
annual_inc_joint                  100.00
dti_joint                         100.00
verification_status_joint         100.00
acc_now_delinq                      0.00
tot_coll_amt                      100.00
tot_cur_bal                       100.00
open_acc_6m                       100.00
open_il_6m                        100.00
open_il_12m                       100.00
open_il_24m                       100.00
mths_since_rcnt_il                100.00
total_bal_il                      100.00
il_util                           100.00
open_rv_12m                       100.00
open_rv_24m                       100.00
max_bal_bc                        100.00
all_util                          100.00
total_rev_hi_lim                  100.00
inq_fi                            100.00
total_cu_tl                       100.00
inq_last_12m                      100.00
acc_open_past_24mths              100.00
avg_cur_bal                       100.00
bc_open_to_buy                    100.00
bc_util                           100.00
chargeoff_within_12_mths            0.14
delinq_amnt                         0.00
mo_sin_old_il_acct                100.00
mo_sin_old_rev_tl_op              100.00
mo_sin_rcnt_rev_tl_op             100.00
mo_sin_rcnt_tl                    100.00
mort_acc                          100.00
mths_since_recent_bc              100.00
mths_since_recent_bc_dlq          100.00
mths_since_recent_inq             100.00
mths_since_recent_revol_delinq    100.00
num_accts_ever_120_pd             100.00
num_actv_bc_tl                    100.00
pub_rec_bankruptcies                1.75
tax_liens                           0.10
dtype: float64

In [80]:
loan_data_set = loan_data_set.drop(['num_actv_bc_tl','num_accts_ever_120_pd','mths_since_recent_revol_delinq','mths_since_recent_inq','mths_since_recent_bc_dlq','mths_since_recent_bc','mort_acc','mo_sin_rcnt_tl','mo_sin_rcnt_rev_tl_op','mo_sin_old_rev_tl_op'], axis =1)

In [81]:
round(loan_data_set.isnull().sum()/len(loan_data_set)*100,2)

id                               0.00
member_id                        0.00
loan_amnt                        0.00
funded_amnt                      0.00
funded_amnt_inv                  0.00
term                             0.00
int_rate                         0.00
installment                      0.00
grade                            0.00
sub_grade                        0.00
emp_title                        6.19
emp_length                       2.71
home_ownership                   0.00
annual_inc                       0.00
verification_status              0.00
issue_d                          0.00
loan_status                      0.00
pymnt_plan                       0.00
url                              0.00
desc                            32.58
purpose                          0.00
title                            0.03
zip_code                         0.00
addr_state                       0.00
dti                              0.00
delinq_2yrs                      0.00
earliest_cr_line                 0.00
inq_last_6mths                   0.00
mths_since_last_delinq          64.66
mths_since_last_record          92.99
open_acc                         0.00
pub_rec                          0.00
revol_bal                        0.00
revol_util                       0.13
total_acc                        0.00
initial_list_status              0.00
out_prncp                        0.00
out_prncp_inv                    0.00
total_pymnt                      0.00
total_pymnt_inv                  0.00
total_rec_prncp                  0.00
total_rec_int                    0.00
total_rec_late_fee               0.00
recoveries                       0.00
collection_recovery_fee          0.00
last_pymnt_d                     0.18
last_pymnt_amnt                  0.00
next_pymnt_d                    97.13
last_credit_pull_d               0.01
collections_12_mths_ex_med       0.14
mths_since_last_major_derog    100.00
policy_code                      0.00
application_type                 0.00
annual_inc_joint               100.00
dti_joint                      100.00
verification_status_joint      100.00
acc_now_delinq                   0.00
tot_coll_amt                   100.00
tot_cur_bal                    100.00
open_acc_6m                    100.00
open_il_6m                     100.00
open_il_12m                    100.00
open_il_24m                    100.00
mths_since_rcnt_il             100.00
total_bal_il                   100.00
il_util                        100.00
open_rv_12m                    100.00
open_rv_24m                    100.00
max_bal_bc                     100.00
all_util                       100.00
total_rev_hi_lim               100.00
inq_fi                         100.00
total_cu_tl                    100.00
inq_last_12m                   100.00
acc_open_past_24mths           100.00
avg_cur_bal                    100.00
bc_open_to_buy                 100.00
bc_util                        100.00
chargeoff_within_12_mths         0.14
delinq_amnt                      0.00
mo_sin_old_il_acct             100.00
pub_rec_bankruptcies             1.75
tax_liens                        0.10
dtype: float64

In [83]:
loan_data_set = loan_data_set.drop(['mo_sin_old_il_acct','bc_util','bc_open_to_buy','avg_cur_bal','acc_open_past_24mths','inq_last_12m','total_cu_tl','all_util','inq_fi','total_rev_hi_lim'], axis =1)

In [84]:
round(loan_data_set.isnull().sum()/len(loan_data_set)*100,2)

id                               0.00
member_id                        0.00
loan_amnt                        0.00
funded_amnt                      0.00
funded_amnt_inv                  0.00
term                             0.00
int_rate                         0.00
installment                      0.00
grade                            0.00
sub_grade                        0.00
emp_title                        6.19
emp_length                       2.71
home_ownership                   0.00
annual_inc                       0.00
verification_status              0.00
issue_d                          0.00
loan_status                      0.00
pymnt_plan                       0.00
url                              0.00
desc                            32.58
purpose                          0.00
title                            0.03
zip_code                         0.00
addr_state                       0.00
dti                              0.00
delinq_2yrs                      0.00
earliest_cr_line                 0.00
inq_last_6mths                   0.00
mths_since_last_delinq          64.66
mths_since_last_record          92.99
open_acc                         0.00
pub_rec                          0.00
revol_bal                        0.00
revol_util                       0.13
total_acc                        0.00
initial_list_status              0.00
out_prncp                        0.00
out_prncp_inv                    0.00
total_pymnt                      0.00
total_pymnt_inv                  0.00
total_rec_prncp                  0.00
total_rec_int                    0.00
total_rec_late_fee               0.00
recoveries                       0.00
collection_recovery_fee          0.00
last_pymnt_d                     0.18
last_pymnt_amnt                  0.00
next_pymnt_d                    97.13
last_credit_pull_d               0.01
collections_12_mths_ex_med       0.14
mths_since_last_major_derog    100.00
policy_code                      0.00
application_type                 0.00
annual_inc_joint               100.00
dti_joint                      100.00
verification_status_joint      100.00
acc_now_delinq                   0.00
tot_coll_amt                   100.00
tot_cur_bal                    100.00
open_acc_6m                    100.00
open_il_6m                     100.00
open_il_12m                    100.00
open_il_24m                    100.00
mths_since_rcnt_il             100.00
total_bal_il                   100.00
il_util                        100.00
open_rv_12m                    100.00
open_rv_24m                    100.00
max_bal_bc                     100.00
chargeoff_within_12_mths         0.14
delinq_amnt                      0.00
pub_rec_bankruptcies             1.75
tax_liens                        0.10
dtype: float64

In [85]:
loan_data_set = loan_data_set.drop(['max_bal_bc','open_rv_24m','open_rv_12m','il_util','total_bal_il','mths_since_rcnt_il','open_il_24m','open_il_12m','open_il_6m','open_acc_6m'], axis =1)

In [86]:
round(loan_data_set.isnull().sum()/len(loan_data_set)*100,2)

id                               0.00
member_id                        0.00
loan_amnt                        0.00
funded_amnt                      0.00
funded_amnt_inv                  0.00
term                             0.00
int_rate                         0.00
installment                      0.00
grade                            0.00
sub_grade                        0.00
emp_title                        6.19
emp_length                       2.71
home_ownership                   0.00
annual_inc                       0.00
verification_status              0.00
issue_d                          0.00
loan_status                      0.00
pymnt_plan                       0.00
url                              0.00
desc                            32.58
purpose                          0.00
title                            0.03
zip_code                         0.00
addr_state                       0.00
dti                              0.00
delinq_2yrs                      0.00
earliest_cr_line                 0.00
inq_last_6mths                   0.00
mths_since_last_delinq          64.66
mths_since_last_record          92.99
open_acc                         0.00
pub_rec                          0.00
revol_bal                        0.00
revol_util                       0.13
total_acc                        0.00
initial_list_status              0.00
out_prncp                        0.00
out_prncp_inv                    0.00
total_pymnt                      0.00
total_pymnt_inv                  0.00
total_rec_prncp                  0.00
total_rec_int                    0.00
total_rec_late_fee               0.00
recoveries                       0.00
collection_recovery_fee          0.00
last_pymnt_d                     0.18
last_pymnt_amnt                  0.00
next_pymnt_d                    97.13
last_credit_pull_d               0.01
collections_12_mths_ex_med       0.14
mths_since_last_major_derog    100.00
policy_code                      0.00
application_type                 0.00
annual_inc_joint               100.00
dti_joint                      100.00
verification_status_joint      100.00
acc_now_delinq                   0.00
tot_coll_amt                   100.00
tot_cur_bal                    100.00
chargeoff_within_12_mths         0.14
delinq_amnt                      0.00
pub_rec_bankruptcies             1.75
tax_liens                        0.10
dtype: float64

In [87]:
loan_data_set = loan_data_set.drop(['tot_cur_bal','tot_coll_amt','verification_status_joint','dti_joint','annual_inc_joint','mths_since_last_major_derog','next_pymnt_d','mths_since_last_record'], axis =1)

In [88]:
round(loan_data_set.isnull().sum()/len(loan_data_set)*100,2)

id                             0.00
member_id                      0.00
loan_amnt                      0.00
funded_amnt                    0.00
funded_amnt_inv                0.00
term                           0.00
int_rate                       0.00
installment                    0.00
grade                          0.00
sub_grade                      0.00
emp_title                      6.19
emp_length                     2.71
home_ownership                 0.00
annual_inc                     0.00
verification_status            0.00
issue_d                        0.00
loan_status                    0.00
pymnt_plan                     0.00
url                            0.00
desc                          32.58
purpose                        0.00
title                          0.03
zip_code                       0.00
addr_state                     0.00
dti                            0.00
delinq_2yrs                    0.00
earliest_cr_line               0.00
inq_last_6mths                 0.00
mths_since_last_delinq        64.66
open_acc                       0.00
pub_rec                        0.00
revol_bal                      0.00
revol_util                     0.13
total_acc                      0.00
initial_list_status            0.00
out_prncp                      0.00
out_prncp_inv                  0.00
total_pymnt                    0.00
total_pymnt_inv                0.00
total_rec_prncp                0.00
total_rec_int                  0.00
total_rec_late_fee             0.00
recoveries                     0.00
collection_recovery_fee        0.00
last_pymnt_d                   0.18
last_pymnt_amnt                0.00
last_credit_pull_d             0.01
collections_12_mths_ex_med     0.14
policy_code                    0.00
application_type               0.00
acc_now_delinq                 0.00
chargeoff_within_12_mths       0.14
delinq_amnt                    0.00
pub_rec_bankruptcies           1.75
tax_liens                      0.10
dtype: float64

In [90]:
loan_data_set.mths_since_last_delinq.describe()

count    14035.000000
mean        35.900962
std         22.020060
min          0.000000
25%         18.000000
50%         34.000000
75%         52.000000
max        120.000000
Name: mths_since_last_delinq, dtype: float64

In [92]:
loan_data_set.desc.value_counts()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           210
Debt Consolidation                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           8
Camping Membership                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           6
credit card consolidation                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    3
Personal Loan                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                3
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ...
  Borrower added on 07/17/11 > This loan will be used to consolidate 3 credit card accounts. Interest rates have risen in the last couple of years and I need to pay off these accounts before the rates climb again. My interest rates are between 20% and 30%. I have a Union-protected and very stable job. I have no plans in leaving my current employer since it offers me a great working environment, great benefits, and a great retirement package including  401(k) and pension plans. I pay my bills on time every month and plan to keep doing so until I'm debt free. My monthly expenses are $1000 for rent, $300 in car expenses (including insurance and gas), about $400 in groceries, and about $100 in utilities (electricity and gas, we don't have cable) I pay 50% of my household expenses.<br/>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     1
  Borrower added on 11/09/11 > Used to pay taxes I owe and hold me until my annual bonus in April<br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        1
  Borrower added on 04/03/10 > I'll be using these funds to jumpstart an open-source initiative to develop a mobile application similar to Pandora or Grooveshark. If you're not familiar with these services, I encourage you to check them out (just google either one). <br/><br/>I have a track record of excellent credit and have NEVER missed a payment on anything in my life.I don't plan on starting now :). So invest with confidence.<br/>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       1
INVESTMENT OPPORTUNITY                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       1

In [93]:
loan_data_set.emp_length

0        10+ years
1         < 1 year
2        10+ years
3        10+ years
4           1 year
           ...
39712      4 years
39713      3 years
39714     < 1 year
39715     < 1 year
39716     < 1 year
Name: emp_length, Length: 39717, dtype: object

In [95]:
loan_data_set.emp_title.head(40)

0                                          NaN
1                                        Ryder
2                                          NaN
3                          AIR RESOURCES BOARD
4                     University Medical Group
5                         Veolia Transportaton
6                    Southern Star Photography
7                              MKC Accounting
8                                          NaN
9                                    Starbucks
10                       Southwest Rural metro
11                                        UCLA
12         Va. Dept of Conservation/Recreation
13                                      Target
14                                       SFMTA
15                    Internal revenue Service
16                           Chin's Restaurant
17                                    Duracell
18                       Connection Inspection
19                Network Interpreting Service
20            Archdiocese of Galveston Houston
21                              Osram Sylvania
22                                   Value Air
23                            Wells Fargo Bank
24                             bmg-educational
25              Winfield Pathology Consultants
26                                 nyc transit
27                                   Frito Lay
28     Shands Hospital at the University of Fl
29                              Oakridge homes
30                                         NaN
31          Audubon Mutual Housing Corporation
32                            US Legal Support
33                      Good Samaritan Society
34                        GREG BARRETT DRYWALL
35                             Sharp Lawn Inc.
36                       Department of Justice
37                             Gateway Hospice
38                          Cox Communications
39    United States Infrastructure Corporation
Name: emp_title, dtype: object

In [2]:
print("Hello")

Hello